# https://taskfile.dev

version: '3'

tasks:
  autogit:
    cmds:
      - task: skip_repo_stuff
  run:
    cmds:
      - npm install
      - npm run dev
    silent: true
  default:
    cmds:
      - codium .
    silent: true
